version: '3.8'

services:
  nginx22:
    image: nginx:alpine
    container_name: nginx22
    ports:
      - "9090:80"  # 将宿主机的 9090 端口映射到容器的 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载自定义 Nginx 配置文件
      - ./logs/nginx:/var/log/nginx  # 挂载 Nginx 日志目录（可选）
    depends_on:
      - luozhuohua11
      - luozhuohua22
    networks:
      - vue-network

  luozhuohua11:
    build: ./luozhuohua  # 构建 luozhuohua 目录中的 Dockerfile
    container_name: luozhuohua11
    volumes:
      - ./luozhuohua/dist:/usr/share/nginx/html  # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  luozhuohua22:
    build: ./luozhuohua2  # 构建 luozhuohua2 目录中的 Dockerfile
    container_name: luozhuohua22
    volumes:
      - ./luozhuohua2/dist:/usr/share/nginx/html  # 挂载本地 dist 目录到容器
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge  # 使用桥接网络