version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # 挂载 Caddy 配置文件
      - ./caddy_data:/data # 存储 SSL 证书
      - ./caddy_config:/config # 存储 Caddy 配置
    networks:
      - vue-network

  index:
    build: ./index # 构建 index 目录中的 Dockerfile
    container_name: index
    volumes:
      - ./index/:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  renyimen:
    build: ./renyimen # 构建 renyimen 目录中的 Dockerfile
    container_name: renyimen
    volumes:
      - ./renyimen/dist:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  luozhuohua11:
    build: ./luozhuohua # 构建 luozhuohua 目录中的 Dockerfile
    container_name: luozhuohua11
    volumes:
      - ./luozhuohua/dist:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  luozhuohua22:
    build: ./luozhuohua2 # 构建 luozhuohua2 目录中的 Dockerfile
    container_name: luozhuohua22
    volumes:
      - ./luozhuohua2/dist:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  luozhuohua33:
    build: ./luozhuohua3 # 构建 luozhuohua3 目录中的 Dockerfile
    container_name: luozhuohua33
    volumes:
      - ./luozhuohua3/dist:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  luozhuohua44:
    build: ./luozhuohua4 # 构建 luozhuohua4 目录中的 Dockerfile
    container_name: luozhuohua44
    volumes:
      - ./luozhuohua4/dist:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  luozhuohua55:
    build: ./luozhuohua5 # 构建 luozhuohua5 目录中的 Dockerfile
    container_name: luozhuohua55
    volumes:
      - ./luozhuohua5/dist:/usr/share/nginx/html # 挂载本地 dist 目录到容器
    networks:
      - vue-network

  # 静态资源服务
  static:
    build: ./static
    container_name: static
    restart: unless-stopped
    volumes:
      - ./static:/usr/share/nginx/static  # 挂载静态资源目录
    networks:
      - vue-network
    expose:
      - "80"  # 暴露静态服务的 80 端口

networks:
  vue-network:
    driver: bridge # 使用桥接网络
